# ES8311 audio codec + NS4150B amplifier + MEMS microphone.
# Configure substitutions in build.yaml for different sample rates or pins.

substitutions:
  cardputer_audio_i2c_bus: "bus_a" # I2C bus for ES8311 control.
  cardputer_audio_i2c_addr: "0x18" # From I2C scan; ES8311 addr0 (alt addr1 is 0x19).
  cardputer_audio_i2s_bclk: "41"
  cardputer_audio_i2s_lrck: "43"
  cardputer_audio_i2s_dout: "42" # Speaker data out.
  cardputer_audio_i2s_din: "46" # Microphone data in.
  cardputer_audio_sample_rate: "16000"
  cardputer_audio_bits: "16bit"
  cardputer_audio_speaker_channel: "mono" # Mono speaker output.
  cardputer_audio_mic_channel: "right" # Use right channel for the mic.
  cardputer_audio_use_mclk: "false" # No MCLK pin on this board.
  cardputer_audio_use_microphone: "true"

i2s_audio:
  - id: cardputer_i2s
    i2s_lrclk_pin: ${cardputer_audio_i2s_lrck}
    i2s_bclk_pin: ${cardputer_audio_i2s_bclk}

es8311:
  id: cardputer_audio_dac
  i2c_id: ${cardputer_audio_i2c_bus}
  address: ${cardputer_audio_i2c_addr}
  sample_rate: ${cardputer_audio_sample_rate}
  bits_per_sample: ${cardputer_audio_bits}
  use_mclk: ${cardputer_audio_use_mclk}
  use_microphone: ${cardputer_audio_use_microphone}

speaker:
  - platform: i2s_audio
    id: cardputer_speaker
    i2s_audio_id: cardputer_i2s
    dac_type: external
    i2s_dout_pin: ${cardputer_audio_i2s_dout}
    audio_dac: cardputer_audio_dac
    sample_rate: ${cardputer_audio_sample_rate}
    bits_per_sample: ${cardputer_audio_bits}
    channel: ${cardputer_audio_speaker_channel}

microphone:
  - platform: i2s_audio
    id: cardputer_microphone
    i2s_audio_id: cardputer_i2s
    adc_type: external
    i2s_din_pin: ${cardputer_audio_i2s_din}
    sample_rate: ${cardputer_audio_sample_rate}
    bits_per_sample: ${cardputer_audio_bits}
    channel: ${cardputer_audio_mic_channel}
