# BMI270 6-axis IMU.
# ESPHome 2025.12.1 does not include a BMI270 component.
# Keep these substitutions for a future custom/external component.

substitutions:
  cardputer_imu_i2c_bus: "bus_a" # I2C bus for the IMU.
  cardputer_imu_addr: "0x69" # From I2C scan; BMI270 alt address (0x68 is common default).
